export const blogsData = [
    {
        id: 1,
        title: 'Html',
        body: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat, nesciunt facilis dicta deserunt eaque in dignissimos, beatae, iusto deleniti quasi ratione aspernatur illum dolore officiis animi architecto? Consequuntur perspiciatis saepe nisi accusantium reiciendis accusamus rem praesentium odit suscipit deserunt maxime aperiam nemo iure nostrum esse aspernatur non, quidem ut deleniti quisquam porro laborum iusto. Ab nemo doloremque, neque aperiam sunt quibusdam quasi exercitationem cum enim iste deleniti adipisci repellat distinctio fuga non nulla quas ullam voluptates ipsa debitis est maiores iure! Mollitia natus vel exercitationem, aut error neque optio facilis accusamus voluptates quasi, saepe ea? Amet, soluta in? Velit pariatur tempora eaque obcaecati eveniet maiores accusantium eius assumenda, corporis autem nihil odit, quae id quidem fuga nulla unde, repellat voluptas veniam. At, pariatur dolores nostrum voluptate natus voluptates accusamus ad corporis accusantium sequi laudantium deleniti, esse vel amet molestiae libero asperiores, rem aliquam! Porro exercitationem labore nostrum sunt perferendis dolorum debitis fuga nihil soluta asperiores, velit inventore id esse magnam tenetur aliquid maiores molestiae aut consequuntur! Explicabo dolorem laboriosam illum quaerat tempora alias qui adipisci incidunt sapiente id, possimus fuga ex, impedit nemo! In omnis, autem aliquid, nulla deserunt ex, saepe accusantium illo repellendus eum quia cupiditate amet consectetur odio. Alias vero eum provident ipsum fuga corrupti nam ipsam, sint dignissimos amet sed, accusantium maxime deserunt asperiores error libero sapiente perferendis placeat aperiam laboriosam illum exercitationem adipisci minima? Quod, cupiditate voluptas officia est, expedita perferendis ullam illo, quas facilis asperiores sequi voluptate doloremque. Id unde dolor vel officiis facere nobis ab deserunt consequatur commodi.'
    },
    {
        id: 2,
        title: 'Css',
        body: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat, nesciunt facilis dicta deserunt eaque in dignissimos, beatae, iusto deleniti quasi ratione aspernatur illum dolore officiis animi architecto? Consequuntur perspiciatis saepe nisi accusantium reiciendis accusamus rem praesentium odit suscipit deserunt maxime aperiam nemo iure nostrum esse aspernatur non, quidem ut deleniti quisquam porro laborum iusto. Ab nemo doloremque, neque aperiam sunt quibusdam quasi exercitationem cum enim iste deleniti adipisci repellat distinctio fuga non nulla quas ullam voluptates ipsa debitis est maiores iure! Mollitia natus vel exercitationem, aut error neque optio facilis accusamus voluptates quasi, saepe ea? Amet, soluta in? Velit pariatur tempora eaque obcaecati eveniet maiores accusantium eius assumenda, corporis autem nihil odit, quae id quidem fuga nulla unde, repellat voluptas veniam. At, pariatur dolores nostrum voluptate natus voluptates accusamus ad corporis accusantium sequi laudantium deleniti, esse vel amet molestiae libero asperiores, rem aliquam! Porro exercitationem labore nostrum sunt perferendis dolorum debitis fuga nihil soluta asperiores, velit inventore id esse magnam tenetur aliquid maiores molestiae aut consequuntur! Explicabo dolorem laboriosam illum quaerat tempora alias qui adipisci incidunt sapiente id, possimus fuga ex, impedit nemo! In omnis, autem aliquid, nulla deserunt ex, saepe accusantium illo repellendus eum quia cupiditate amet consectetur odio. Alias vero eum provident ipsum fuga corrupti nam ipsam, sint dignissimos amet sed, accusantium maxime deserunt asperiores error libero sapiente perferendis placeat aperiam laboriosam illum exercitationem adipisci minima? Quod, cupiditate voluptas officia est, expedita perferendis ullam illo, quas facilis asperiores sequi voluptate doloremque. Id unde dolor vel officiis facere nobis ab deserunt consequatur commodi.'
    },
    {
        id: 3,
        title: 'javaScript',
        body: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat, nesciunt facilis dicta deserunt eaque in dignissimos, beatae, iusto deleniti quasi ratione aspernatur illum dolore officiis animi architecto? Consequuntur perspiciatis saepe nisi accusantium reiciendis accusamus rem praesentium odit suscipit deserunt maxime aperiam nemo iure nostrum esse aspernatur non, quidem ut deleniti quisquam porro laborum iusto. Ab nemo doloremque, neque aperiam sunt quibusdam quasi exercitationem cum enim iste deleniti adipisci repellat distinctio fuga non nulla quas ullam voluptates ipsa debitis est maiores iure! Mollitia natus vel exercitationem, aut error neque optio facilis accusamus voluptates quasi, saepe ea? Amet, soluta in? Velit pariatur tempora eaque obcaecati eveniet maiores accusantium eius assumenda, corporis autem nihil odit, quae id quidem fuga nulla unde, repellat voluptas veniam. At, pariatur dolores nostrum voluptate natus voluptates accusamus ad corporis accusantium sequi laudantium deleniti, esse vel amet molestiae libero asperiores, rem aliquam! Porro exercitationem labore nostrum sunt perferendis dolorum debitis fuga nihil soluta asperiores, velit inventore id esse magnam tenetur aliquid maiores molestiae aut consequuntur! Explicabo dolorem laboriosam illum quaerat tempora alias qui adipisci incidunt sapiente id, possimus fuga ex, impedit nemo! In omnis, autem aliquid, nulla deserunt ex, saepe accusantium illo repellendus eum quia cupiditate amet consectetur odio. Alias vero eum provident ipsum fuga corrupti nam ipsam, sint dignissimos amet sed, accusantium maxime deserunt asperiores error libero sapiente perferendis placeat aperiam laboriosam illum exercitationem adipisci minima? Quod, cupiditate voluptas officia est, expedita perferendis ullam illo, quas facilis asperiores sequi voluptate doloremque. Id unde dolor vel officiis facere nobis ab deserunt consequatur commodi.'
    },
    {
        id: 4,
        title: 'React js',
        body: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat, nesciunt facilis dicta deserunt eaque in dignissimos, beatae, iusto deleniti quasi ratione aspernatur illum dolore officiis animi architecto? Consequuntur perspiciatis saepe nisi accusantium reiciendis accusamus rem praesentium odit suscipit deserunt maxime aperiam nemo iure nostrum esse aspernatur non, quidem ut deleniti quisquam porro laborum iusto. Ab nemo doloremque, neque aperiam sunt quibusdam quasi exercitationem cum enim iste deleniti adipisci repellat distinctio fuga non nulla quas ullam voluptates ipsa debitis est maiores iure! Mollitia natus vel exercitationem, aut error neque optio facilis accusamus voluptates quasi, saepe ea? Amet, soluta in? Velit pariatur tempora eaque obcaecati eveniet maiores accusantium eius assumenda, corporis autem nihil odit, quae id quidem fuga nulla unde, repellat voluptas veniam. At, pariatur dolores nostrum voluptate natus voluptates accusamus ad corporis accusantium sequi laudantium deleniti, esse vel amet molestiae libero asperiores, rem aliquam! Porro exercitationem labore nostrum sunt perferendis dolorum debitis fuga nihil soluta asperiores, velit inventore id esse magnam tenetur aliquid maiores molestiae aut consequuntur! Explicabo dolorem laboriosam illum quaerat tempora alias qui adipisci incidunt sapiente id, possimus fuga ex, impedit nemo! In omnis, autem aliquid, nulla deserunt ex, saepe accusantium illo repellendus eum quia cupiditate amet consectetur odio. Alias vero eum provident ipsum fuga corrupti nam ipsam, sint dignissimos amet sed, accusantium maxime deserunt asperiores error libero sapiente perferendis placeat aperiam laboriosam illum exercitationem adipisci minima? Quod, cupiditate voluptas officia est, expedita perferendis ullam illo, quas facilis asperiores sequi voluptate doloremque. Id unde dolor vel officiis facere nobis ab deserunt consequatur commodi.'
    },
    {
        id: 5,
        title: 'Node js',
        body: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quaerat, nesciunt facilis dicta deserunt eaque in dignissimos, beatae, iusto deleniti quasi ratione aspernatur illum dolore officiis animi architecto? Consequuntur perspiciatis saepe nisi accusantium reiciendis accusamus rem praesentium odit suscipit deserunt maxime aperiam nemo iure nostrum esse aspernatur non, quidem ut deleniti quisquam porro laborum iusto. Ab nemo doloremque, neque aperiam sunt quibusdam quasi exercitationem cum enim iste deleniti adipisci repellat distinctio fuga non nulla quas ullam voluptates ipsa debitis est maiores iure! Mollitia natus vel exercitationem, aut error neque optio facilis accusamus voluptates quasi, saepe ea? Amet, soluta in? Velit pariatur tempora eaque obcaecati eveniet maiores accusantium eius assumenda, corporis autem nihil odit, quae id quidem fuga nulla unde, repellat voluptas veniam. At, pariatur dolores nostrum voluptate natus voluptates accusamus ad corporis accusantium sequi laudantium deleniti, esse vel amet molestiae libero asperiores, rem aliquam! Porro exercitationem labore nostrum sunt perferendis dolorum debitis fuga nihil soluta asperiores, velit inventore id esse magnam tenetur aliquid maiores molestiae aut consequuntur! Explicabo dolorem laboriosam illum quaerat tempora alias qui adipisci incidunt sapiente id, possimus fuga ex, impedit nemo! In omnis, autem aliquid, nulla deserunt ex, saepe accusantium illo repellendus eum quia cupiditate amet consectetur odio. Alias vero eum provident ipsum fuga corrupti nam ipsam, sint dignissimos amet sed, accusantium maxime deserunt asperiores error libero sapiente perferendis placeat aperiam laboriosam illum exercitationem adipisci minima? Quod, cupiditate voluptas officia est, expedita perferendis ullam illo, quas facilis asperiores sequi voluptate doloremque. Id unde dolor vel officiis facere nobis ab deserunt consequatur commodi.'
    },
]